// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proxy.proto

package gproxy

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CreateProxyStatRequest struct {
	ProxyStat *ProxyStat `protobuf:"bytes,1,opt,name=proxy_stat,json=proxyStat,proto3" json:"proxy_stat,omitempty"`
}

func (m *CreateProxyStatRequest) Reset()      { *m = CreateProxyStatRequest{} }
func (*CreateProxyStatRequest) ProtoMessage() {}
func (*CreateProxyStatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{0}
}
func (m *CreateProxyStatRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateProxyStatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateProxyStatRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateProxyStatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProxyStatRequest.Merge(m, src)
}
func (m *CreateProxyStatRequest) XXX_Size() int {
	return m.Size()
}
func (m *CreateProxyStatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProxyStatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProxyStatRequest proto.InternalMessageInfo

func (m *CreateProxyStatRequest) GetProxyStat() *ProxyStat {
	if m != nil {
		return m.ProxyStat
	}
	return nil
}

type CreateProxyStatResponse struct {
	ProxyStat *ProxyStat `protobuf:"bytes,1,opt,name=proxy_stat,json=proxyStat,proto3" json:"proxy_stat,omitempty"`
}

func (m *CreateProxyStatResponse) Reset()      { *m = CreateProxyStatResponse{} }
func (*CreateProxyStatResponse) ProtoMessage() {}
func (*CreateProxyStatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{1}
}
func (m *CreateProxyStatResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateProxyStatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateProxyStatResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateProxyStatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProxyStatResponse.Merge(m, src)
}
func (m *CreateProxyStatResponse) XXX_Size() int {
	return m.Size()
}
func (m *CreateProxyStatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProxyStatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProxyStatResponse proto.InternalMessageInfo

func (m *CreateProxyStatResponse) GetProxyStat() *ProxyStat {
	if m != nil {
		return m.ProxyStat
	}
	return nil
}

type GetNextProxyRequest struct {
}

func (m *GetNextProxyRequest) Reset()      { *m = GetNextProxyRequest{} }
func (*GetNextProxyRequest) ProtoMessage() {}
func (*GetNextProxyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{2}
}
func (m *GetNextProxyRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetNextProxyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetNextProxyRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetNextProxyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNextProxyRequest.Merge(m, src)
}
func (m *GetNextProxyRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetNextProxyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNextProxyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNextProxyRequest proto.InternalMessageInfo

type GetNextProxyResponse struct {
	ProxyItem *ProxyItem `protobuf:"bytes,1,opt,name=proxy_item,json=proxyItem,proto3" json:"proxy_item,omitempty"`
}

func (m *GetNextProxyResponse) Reset()      { *m = GetNextProxyResponse{} }
func (*GetNextProxyResponse) ProtoMessage() {}
func (*GetNextProxyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{3}
}
func (m *GetNextProxyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetNextProxyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetNextProxyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetNextProxyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNextProxyResponse.Merge(m, src)
}
func (m *GetNextProxyResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetNextProxyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNextProxyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNextProxyResponse proto.InternalMessageInfo

func (m *GetNextProxyResponse) GetProxyItem() *ProxyItem {
	if m != nil {
		return m.ProxyItem
	}
	return nil
}

type GetBestProxyRequest struct {
}

func (m *GetBestProxyRequest) Reset()      { *m = GetBestProxyRequest{} }
func (*GetBestProxyRequest) ProtoMessage() {}
func (*GetBestProxyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{4}
}
func (m *GetBestProxyRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetBestProxyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetBestProxyRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetBestProxyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBestProxyRequest.Merge(m, src)
}
func (m *GetBestProxyRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetBestProxyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBestProxyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBestProxyRequest proto.InternalMessageInfo

type GetBestProxyResponse struct {
	ProxyItem *ProxyItem `protobuf:"bytes,1,opt,name=proxy_item,json=proxyItem,proto3" json:"proxy_item,omitempty"`
}

func (m *GetBestProxyResponse) Reset()      { *m = GetBestProxyResponse{} }
func (*GetBestProxyResponse) ProtoMessage() {}
func (*GetBestProxyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{5}
}
func (m *GetBestProxyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetBestProxyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetBestProxyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetBestProxyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBestProxyResponse.Merge(m, src)
}
func (m *GetBestProxyResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetBestProxyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBestProxyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBestProxyResponse proto.InternalMessageInfo

func (m *GetBestProxyResponse) GetProxyItem() *ProxyItem {
	if m != nil {
		return m.ProxyItem
	}
	return nil
}

type CreateProxyRequest struct {
	ProxyItem *ProxyItem `protobuf:"bytes,1,opt,name=proxy_item,json=proxyItem,proto3" json:"proxy_item,omitempty"`
}

func (m *CreateProxyRequest) Reset()      { *m = CreateProxyRequest{} }
func (*CreateProxyRequest) ProtoMessage() {}
func (*CreateProxyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{6}
}
func (m *CreateProxyRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateProxyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateProxyRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateProxyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProxyRequest.Merge(m, src)
}
func (m *CreateProxyRequest) XXX_Size() int {
	return m.Size()
}
func (m *CreateProxyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProxyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProxyRequest proto.InternalMessageInfo

func (m *CreateProxyRequest) GetProxyItem() *ProxyItem {
	if m != nil {
		return m.ProxyItem
	}
	return nil
}

type CreateProxyResponse struct {
	ProxyItem *ProxyItem `protobuf:"bytes,1,opt,name=proxy_item,json=proxyItem,proto3" json:"proxy_item,omitempty"`
}

func (m *CreateProxyResponse) Reset()      { *m = CreateProxyResponse{} }
func (*CreateProxyResponse) ProtoMessage() {}
func (*CreateProxyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{7}
}
func (m *CreateProxyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateProxyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateProxyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateProxyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProxyResponse.Merge(m, src)
}
func (m *CreateProxyResponse) XXX_Size() int {
	return m.Size()
}
func (m *CreateProxyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProxyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProxyResponse proto.InternalMessageInfo

func (m *CreateProxyResponse) GetProxyItem() *ProxyItem {
	if m != nil {
		return m.ProxyItem
	}
	return nil
}

type ProxyCountry struct {
	CountryId   int64      `protobuf:"varint,1,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	CountryName string     `protobuf:"bytes,2,opt,name=country_name,json=countryName,proto3" json:"country_name,omitempty"`
	CountryCode string     `protobuf:"bytes,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	CreatedAt   *time.Time `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at,omitempty"`
}

func (m *ProxyCountry) Reset()      { *m = ProxyCountry{} }
func (*ProxyCountry) ProtoMessage() {}
func (*ProxyCountry) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{8}
}
func (m *ProxyCountry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProxyCountry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProxyCountry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProxyCountry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyCountry.Merge(m, src)
}
func (m *ProxyCountry) XXX_Size() int {
	return m.Size()
}
func (m *ProxyCountry) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyCountry.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyCountry proto.InternalMessageInfo

func (m *ProxyCountry) GetCountryId() int64 {
	if m != nil {
		return m.CountryId
	}
	return 0
}

func (m *ProxyCountry) GetCountryName() string {
	if m != nil {
		return m.CountryName
	}
	return ""
}

func (m *ProxyCountry) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *ProxyCountry) GetCreatedAt() *time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type ProxyStat struct {
	//    Удалил бывший PK
	//    int64 stat_id = 1;
	ProxyId    int64 `protobuf:"varint,2,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	ConnTime   int64 `protobuf:"varint,3,opt,name=conn_time,json=connTime,proto3" json:"conn_time,omitempty"`
	ConnStatus bool  `protobuf:"varint,4,opt,name=conn_status,json=connStatus,proto3" json:"conn_status,omitempty"`
	//    Новый PK
	CreatedAt *time.Time `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at,omitempty"`
}

func (m *ProxyStat) Reset()      { *m = ProxyStat{} }
func (*ProxyStat) ProtoMessage() {}
func (*ProxyStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{9}
}
func (m *ProxyStat) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProxyStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProxyStat.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProxyStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyStat.Merge(m, src)
}
func (m *ProxyStat) XXX_Size() int {
	return m.Size()
}
func (m *ProxyStat) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyStat.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyStat proto.InternalMessageInfo

func (m *ProxyStat) GetProxyId() int64 {
	if m != nil {
		return m.ProxyId
	}
	return 0
}

func (m *ProxyStat) GetConnTime() int64 {
	if m != nil {
		return m.ConnTime
	}
	return 0
}

func (m *ProxyStat) GetConnStatus() bool {
	if m != nil {
		return m.ConnStatus
	}
	return false
}

func (m *ProxyStat) GetCreatedAt() *time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type ProxyItem struct {
	ProxyId      int64         `protobuf:"varint,1,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	ProxyIp      string        `protobuf:"bytes,2,opt,name=proxy_ip,json=proxyIp,proto3" json:"proxy_ip,omitempty"`
	ProxyPort    int64         `protobuf:"varint,3,opt,name=proxy_port,json=proxyPort,proto3" json:"proxy_port,omitempty"`
	Anonymity    string        `protobuf:"bytes,5,opt,name=anonymity,proto3" json:"anonymity,omitempty"`
	ProxyCountry *ProxyCountry `protobuf:"bytes,4,opt,name=proxy_country,json=proxyCountry,proto3" json:"proxy_country,omitempty"`
	CreatedAt    *time.Time    `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at,omitempty"`
	UpdatedAt    *time.Time    `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3,stdtime" json:"updated_at,omitempty"`
	DeletedAt    *time.Time    `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3,stdtime" json:"deleted_at,omitempty"`
}

func (m *ProxyItem) Reset()      { *m = ProxyItem{} }
func (*ProxyItem) ProtoMessage() {}
func (*ProxyItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{10}
}
func (m *ProxyItem) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProxyItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProxyItem.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProxyItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyItem.Merge(m, src)
}
func (m *ProxyItem) XXX_Size() int {
	return m.Size()
}
func (m *ProxyItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyItem.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyItem proto.InternalMessageInfo

func (m *ProxyItem) GetProxyId() int64 {
	if m != nil {
		return m.ProxyId
	}
	return 0
}

func (m *ProxyItem) GetProxyIp() string {
	if m != nil {
		return m.ProxyIp
	}
	return ""
}

func (m *ProxyItem) GetProxyPort() int64 {
	if m != nil {
		return m.ProxyPort
	}
	return 0
}

func (m *ProxyItem) GetAnonymity() string {
	if m != nil {
		return m.Anonymity
	}
	return ""
}

func (m *ProxyItem) GetProxyCountry() *ProxyCountry {
	if m != nil {
		return m.ProxyCountry
	}
	return nil
}

func (m *ProxyItem) GetCreatedAt() *time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ProxyItem) GetUpdatedAt() *time.Time {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *ProxyItem) GetDeletedAt() *time.Time {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateProxyStatRequest)(nil), "gproxy.CreateProxyStatRequest")
	proto.RegisterType((*CreateProxyStatResponse)(nil), "gproxy.CreateProxyStatResponse")
	proto.RegisterType((*GetNextProxyRequest)(nil), "gproxy.GetNextProxyRequest")
	proto.RegisterType((*GetNextProxyResponse)(nil), "gproxy.GetNextProxyResponse")
	proto.RegisterType((*GetBestProxyRequest)(nil), "gproxy.GetBestProxyRequest")
	proto.RegisterType((*GetBestProxyResponse)(nil), "gproxy.GetBestProxyResponse")
	proto.RegisterType((*CreateProxyRequest)(nil), "gproxy.CreateProxyRequest")
	proto.RegisterType((*CreateProxyResponse)(nil), "gproxy.CreateProxyResponse")
	proto.RegisterType((*ProxyCountry)(nil), "gproxy.ProxyCountry")
	proto.RegisterType((*ProxyStat)(nil), "gproxy.ProxyStat")
	proto.RegisterType((*ProxyItem)(nil), "gproxy.ProxyItem")
}

func init() { proto.RegisterFile("proxy.proto", fileDescriptor_700b50b08ed8dbaf) }

var fileDescriptor_700b50b08ed8dbaf = []byte{
	// 635 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xf6, 0x36, 0xfd, 0x13, 0x4f, 0xf2, 0xd3, 0x4f, 0x6c, 0x0b, 0x04, 0xb7, 0x6c, 0x8a, 0x4f,
	0xbd, 0xe0, 0xa0, 0x72, 0x81, 0x13, 0x6a, 0x22, 0xd1, 0x96, 0x4a, 0x55, 0xe5, 0xf6, 0xc4, 0x25,
	0x72, 0xe2, 0xc5, 0x44, 0xaa, 0xbd, 0xc6, 0x5e, 0x4b, 0xcd, 0x8d, 0x47, 0xe8, 0x4b, 0x20, 0xf1,
	0x00, 0x1c, 0xb8, 0x72, 0xe3, 0xd8, 0x63, 0x6f, 0x10, 0xe7, 0x05, 0x38, 0x72, 0xe0, 0x80, 0xbc,
	0x5e, 0x27, 0x76, 0x62, 0xa4, 0x34, 0xb7, 0xf5, 0x7c, 0x33, 0xdf, 0x7c, 0x33, 0x3b, 0x3b, 0x86,
	0x9a, 0x1f, 0xb0, 0xab, 0xa1, 0xe1, 0x07, 0x8c, 0x33, 0xbc, 0xee, 0x88, 0x2f, 0xad, 0xe9, 0x30,
	0xe6, 0x5c, 0xd2, 0x96, 0xb0, 0xf6, 0xa2, 0x77, 0x2d, 0x3e, 0x70, 0x69, 0xc8, 0x2d, 0xd7, 0x4f,
	0x1d, 0xb5, 0xa7, 0xce, 0x80, 0xbf, 0x8f, 0x7a, 0x46, 0x9f, 0xb9, 0x2d, 0x87, 0x39, 0x6c, 0xea,
	0x99, 0x7c, 0x89, 0x0f, 0x71, 0x4a, 0xdd, 0xf5, 0x37, 0xf0, 0xa0, 0x13, 0x50, 0x8b, 0xd3, 0xb3,
	0x84, 0xfe, 0x9c, 0x5b, 0xdc, 0xa4, 0x1f, 0x22, 0x1a, 0x72, 0xfc, 0x0c, 0x40, 0xa4, 0xec, 0x86,
	0xdc, 0xe2, 0x0d, 0xb4, 0x8b, 0xf6, 0x6a, 0xfb, 0xf7, 0x8c, 0x54, 0x86, 0x31, 0xf5, 0x56, 0xfd,
	0xec, 0xa8, 0x9f, 0xc0, 0xc3, 0x39, 0xae, 0xd0, 0x67, 0x5e, 0x48, 0x97, 0x20, 0xbb, 0x0f, 0x9b,
	0x87, 0x94, 0x9f, 0xd2, 0x2b, 0x2e, 0x60, 0xa9, 0x4a, 0x3f, 0x82, 0xad, 0xa2, 0x79, 0x36, 0xc1,
	0x80, 0x53, 0xb7, 0x34, 0xc1, 0x31, 0xa7, 0xae, 0x4c, 0x90, 0x1c, 0x65, 0x82, 0x36, 0x0d, 0xcb,
	0x12, 0xe4, 0xcc, 0x4b, 0x27, 0x78, 0x0d, 0x38, 0xd7, 0x8e, 0xb9, 0xb6, 0x2e, 0xcc, 0x73, 0x08,
	0x9b, 0x05, 0x9e, 0xa5, 0x05, 0x7d, 0x41, 0x50, 0x17, 0x40, 0x87, 0x45, 0x1e, 0x0f, 0x86, 0xf8,
	0x31, 0x40, 0x3f, 0x3d, 0x76, 0x07, 0xb6, 0xa0, 0xa8, 0x98, 0xaa, 0xb4, 0x1c, 0xdb, 0xf8, 0x09,
	0xd4, 0x33, 0xd8, 0xb3, 0x5c, 0xda, 0x58, 0xd9, 0x45, 0x7b, 0xaa, 0x59, 0x93, 0xb6, 0x53, 0xcb,
	0xa5, 0x79, 0x97, 0x3e, 0xb3, 0x69, 0xa3, 0x52, 0x70, 0xe9, 0x30, 0x9b, 0xe2, 0x57, 0x00, 0x7d,
	0x21, 0xdf, 0xee, 0x5a, 0xbc, 0xb1, 0x2a, 0x74, 0x6a, 0x46, 0x3a, 0xc6, 0x46, 0x36, 0x9c, 0xc6,
	0x45, 0x36, 0xc6, 0xed, 0xd5, 0xeb, 0x1f, 0x4d, 0x64, 0xaa, 0x32, 0xe6, 0x80, 0xeb, 0x9f, 0x10,
	0xa8, 0x93, 0x11, 0xc1, 0x8f, 0xa0, 0x2a, 0xcb, 0xb6, 0x85, 0xa0, 0x8a, 0xb9, 0x91, 0x56, 0x68,
	0xe3, 0x6d, 0x50, 0xfb, 0xcc, 0xf3, 0xba, 0xc9, 0x93, 0x10, 0x4a, 0x2a, 0x66, 0x35, 0x31, 0x24,
	0xdc, 0xb8, 0x09, 0x35, 0x01, 0x26, 0x03, 0x18, 0x85, 0x42, 0x47, 0xd5, 0x84, 0xc4, 0x74, 0x2e,
	0x2c, 0x33, 0x3a, 0xd7, 0xee, 0xae, 0xf3, 0xcf, 0x8a, 0xd4, 0x99, 0x34, 0xbb, 0xa0, 0x13, 0x15,
	0x75, 0x4e, 0x21, 0x5f, 0xf6, 0x54, 0x42, 0x7e, 0x72, 0x23, 0x29, 0xe4, 0xb3, 0x80, 0xcb, 0x1a,
	0xd2, 0x1b, 0x3c, 0x63, 0x01, 0xc7, 0x3b, 0xa0, 0x5a, 0x1e, 0xf3, 0x86, 0xee, 0x80, 0x0f, 0x85,
	0x44, 0xd5, 0x9c, 0x1a, 0xf0, 0x4b, 0xf8, 0x2f, 0x0d, 0x96, 0xed, 0x97, 0xcd, 0xde, 0x2a, 0x0c,
	0x85, 0xbc, 0x7b, 0xb3, 0xee, 0xe7, 0x27, 0xa1, 0x58, 0xfc, 0xfa, 0x9d, 0x8b, 0x4f, 0x08, 0x22,
	0xdf, 0xce, 0x08, 0x36, 0x16, 0x25, 0x90, 0x31, 0x29, 0x81, 0x4d, 0x2f, 0xa9, 0x24, 0xa8, 0x2e,
	0x4a, 0x20, 0x63, 0x0e, 0xf8, 0xfe, 0xb7, 0x15, 0x58, 0x13, 0x15, 0xe2, 0x23, 0xa8, 0xe5, 0x1e,
	0x0c, 0xd6, 0xb2, 0xfa, 0xe7, 0x5f, 0xa3, 0xb6, 0x5d, 0x8a, 0xa5, 0x2f, 0x4c, 0x57, 0xf0, 0x05,
	0xfc, 0x3f, 0xb3, 0xd1, 0x30, 0x29, 0x89, 0xc8, 0xad, 0x4d, 0xad, 0xf9, 0x4f, 0x7c, 0xc2, 0x7a,
	0x02, 0xf5, 0xfc, 0x0e, 0xc3, 0x13, 0x11, 0x25, 0x0b, 0x4f, 0xdb, 0x29, 0x07, 0x67, 0xc8, 0x26,
	0xfb, 0xaa, 0x40, 0x36, 0xbb, 0xdc, 0x0a, 0x64, 0x73, 0x2b, 0x4e, 0x57, 0xda, 0x2f, 0x6e, 0x47,
	0x44, 0xf9, 0x35, 0x22, 0xe8, 0xf7, 0x88, 0xa0, 0x8f, 0x31, 0x41, 0x9f, 0x63, 0x82, 0xbe, 0xc6,
	0x04, 0x7d, 0x8f, 0x09, 0xba, 0x89, 0x09, 0xfa, 0x19, 0x13, 0x74, 0x3d, 0x26, 0xca, 0xcd, 0x98,
	0x28, 0xb7, 0x63, 0xa2, 0xbc, 0x95, 0xff, 0xa5, 0xde, 0xba, 0xb8, 0xa2, 0xe7, 0x7f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xdf, 0x34, 0xba, 0x4c, 0xb5, 0x06, 0x00, 0x00,
}

func (this *CreateProxyStatRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CreateProxyStatRequest)
	if !ok {
		that2, ok := that.(CreateProxyStatRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ProxyStat.Equal(that1.ProxyStat) {
		return false
	}
	return true
}
func (this *CreateProxyStatResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CreateProxyStatResponse)
	if !ok {
		that2, ok := that.(CreateProxyStatResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ProxyStat.Equal(that1.ProxyStat) {
		return false
	}
	return true
}
func (this *GetNextProxyRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetNextProxyRequest)
	if !ok {
		that2, ok := that.(GetNextProxyRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *GetNextProxyResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetNextProxyResponse)
	if !ok {
		that2, ok := that.(GetNextProxyResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ProxyItem.Equal(that1.ProxyItem) {
		return false
	}
	return true
}
func (this *GetBestProxyRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetBestProxyRequest)
	if !ok {
		that2, ok := that.(GetBestProxyRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *GetBestProxyResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetBestProxyResponse)
	if !ok {
		that2, ok := that.(GetBestProxyResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ProxyItem.Equal(that1.ProxyItem) {
		return false
	}
	return true
}
func (this *CreateProxyRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CreateProxyRequest)
	if !ok {
		that2, ok := that.(CreateProxyRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ProxyItem.Equal(that1.ProxyItem) {
		return false
	}
	return true
}
func (this *CreateProxyResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CreateProxyResponse)
	if !ok {
		that2, ok := that.(CreateProxyResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ProxyItem.Equal(that1.ProxyItem) {
		return false
	}
	return true
}
func (this *ProxyCountry) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ProxyCountry)
	if !ok {
		that2, ok := that.(ProxyCountry)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.CountryId != that1.CountryId {
		return false
	}
	if this.CountryName != that1.CountryName {
		return false
	}
	if this.CountryCode != that1.CountryCode {
		return false
	}
	if that1.CreatedAt == nil {
		if this.CreatedAt != nil {
			return false
		}
	} else if !this.CreatedAt.Equal(*that1.CreatedAt) {
		return false
	}
	return true
}
func (this *ProxyStat) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ProxyStat)
	if !ok {
		that2, ok := that.(ProxyStat)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ProxyId != that1.ProxyId {
		return false
	}
	if this.ConnTime != that1.ConnTime {
		return false
	}
	if this.ConnStatus != that1.ConnStatus {
		return false
	}
	if that1.CreatedAt == nil {
		if this.CreatedAt != nil {
			return false
		}
	} else if !this.CreatedAt.Equal(*that1.CreatedAt) {
		return false
	}
	return true
}
func (this *ProxyItem) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ProxyItem)
	if !ok {
		that2, ok := that.(ProxyItem)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ProxyId != that1.ProxyId {
		return false
	}
	if this.ProxyIp != that1.ProxyIp {
		return false
	}
	if this.ProxyPort != that1.ProxyPort {
		return false
	}
	if this.Anonymity != that1.Anonymity {
		return false
	}
	if !this.ProxyCountry.Equal(that1.ProxyCountry) {
		return false
	}
	if that1.CreatedAt == nil {
		if this.CreatedAt != nil {
			return false
		}
	} else if !this.CreatedAt.Equal(*that1.CreatedAt) {
		return false
	}
	if that1.UpdatedAt == nil {
		if this.UpdatedAt != nil {
			return false
		}
	} else if !this.UpdatedAt.Equal(*that1.UpdatedAt) {
		return false
	}
	if that1.DeletedAt == nil {
		if this.DeletedAt != nil {
			return false
		}
	} else if !this.DeletedAt.Equal(*that1.DeletedAt) {
		return false
	}
	return true
}
func (this *CreateProxyStatRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&gproxy.CreateProxyStatRequest{")
	if this.ProxyStat != nil {
		s = append(s, "ProxyStat: "+fmt.Sprintf("%#v", this.ProxyStat)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CreateProxyStatResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&gproxy.CreateProxyStatResponse{")
	if this.ProxyStat != nil {
		s = append(s, "ProxyStat: "+fmt.Sprintf("%#v", this.ProxyStat)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetNextProxyRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&gproxy.GetNextProxyRequest{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetNextProxyResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&gproxy.GetNextProxyResponse{")
	if this.ProxyItem != nil {
		s = append(s, "ProxyItem: "+fmt.Sprintf("%#v", this.ProxyItem)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetBestProxyRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&gproxy.GetBestProxyRequest{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetBestProxyResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&gproxy.GetBestProxyResponse{")
	if this.ProxyItem != nil {
		s = append(s, "ProxyItem: "+fmt.Sprintf("%#v", this.ProxyItem)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CreateProxyRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&gproxy.CreateProxyRequest{")
	if this.ProxyItem != nil {
		s = append(s, "ProxyItem: "+fmt.Sprintf("%#v", this.ProxyItem)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CreateProxyResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&gproxy.CreateProxyResponse{")
	if this.ProxyItem != nil {
		s = append(s, "ProxyItem: "+fmt.Sprintf("%#v", this.ProxyItem)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ProxyCountry) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&gproxy.ProxyCountry{")
	s = append(s, "CountryId: "+fmt.Sprintf("%#v", this.CountryId)+",\n")
	s = append(s, "CountryName: "+fmt.Sprintf("%#v", this.CountryName)+",\n")
	s = append(s, "CountryCode: "+fmt.Sprintf("%#v", this.CountryCode)+",\n")
	s = append(s, "CreatedAt: "+fmt.Sprintf("%#v", this.CreatedAt)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ProxyStat) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&gproxy.ProxyStat{")
	s = append(s, "ProxyId: "+fmt.Sprintf("%#v", this.ProxyId)+",\n")
	s = append(s, "ConnTime: "+fmt.Sprintf("%#v", this.ConnTime)+",\n")
	s = append(s, "ConnStatus: "+fmt.Sprintf("%#v", this.ConnStatus)+",\n")
	s = append(s, "CreatedAt: "+fmt.Sprintf("%#v", this.CreatedAt)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ProxyItem) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 12)
	s = append(s, "&gproxy.ProxyItem{")
	s = append(s, "ProxyId: "+fmt.Sprintf("%#v", this.ProxyId)+",\n")
	s = append(s, "ProxyIp: "+fmt.Sprintf("%#v", this.ProxyIp)+",\n")
	s = append(s, "ProxyPort: "+fmt.Sprintf("%#v", this.ProxyPort)+",\n")
	s = append(s, "Anonymity: "+fmt.Sprintf("%#v", this.Anonymity)+",\n")
	if this.ProxyCountry != nil {
		s = append(s, "ProxyCountry: "+fmt.Sprintf("%#v", this.ProxyCountry)+",\n")
	}
	s = append(s, "CreatedAt: "+fmt.Sprintf("%#v", this.CreatedAt)+",\n")
	s = append(s, "UpdatedAt: "+fmt.Sprintf("%#v", this.UpdatedAt)+",\n")
	s = append(s, "DeletedAt: "+fmt.Sprintf("%#v", this.DeletedAt)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringProxy(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProxyClient is the client API for Proxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProxyClient interface {
	CreateProxy(ctx context.Context, in *CreateProxyRequest, opts ...grpc.CallOption) (*CreateProxyResponse, error)
	CreateProxyStat(ctx context.Context, in *CreateProxyStatRequest, opts ...grpc.CallOption) (*CreateProxyStatResponse, error)
	GetNextProxy(ctx context.Context, in *GetNextProxyRequest, opts ...grpc.CallOption) (*GetNextProxyResponse, error)
	GetBestProxy(ctx context.Context, in *GetBestProxyRequest, opts ...grpc.CallOption) (*GetBestProxyResponse, error)
}

type proxyClient struct {
	cc *grpc.ClientConn
}

func NewProxyClient(cc *grpc.ClientConn) ProxyClient {
	return &proxyClient{cc}
}

func (c *proxyClient) CreateProxy(ctx context.Context, in *CreateProxyRequest, opts ...grpc.CallOption) (*CreateProxyResponse, error) {
	out := new(CreateProxyResponse)
	err := c.cc.Invoke(ctx, "/gproxy.Proxy/CreateProxy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) CreateProxyStat(ctx context.Context, in *CreateProxyStatRequest, opts ...grpc.CallOption) (*CreateProxyStatResponse, error) {
	out := new(CreateProxyStatResponse)
	err := c.cc.Invoke(ctx, "/gproxy.Proxy/CreateProxyStat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) GetNextProxy(ctx context.Context, in *GetNextProxyRequest, opts ...grpc.CallOption) (*GetNextProxyResponse, error) {
	out := new(GetNextProxyResponse)
	err := c.cc.Invoke(ctx, "/gproxy.Proxy/GetNextProxy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) GetBestProxy(ctx context.Context, in *GetBestProxyRequest, opts ...grpc.CallOption) (*GetBestProxyResponse, error) {
	out := new(GetBestProxyResponse)
	err := c.cc.Invoke(ctx, "/gproxy.Proxy/GetBestProxy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyServer is the server API for Proxy service.
type ProxyServer interface {
	CreateProxy(context.Context, *CreateProxyRequest) (*CreateProxyResponse, error)
	CreateProxyStat(context.Context, *CreateProxyStatRequest) (*CreateProxyStatResponse, error)
	GetNextProxy(context.Context, *GetNextProxyRequest) (*GetNextProxyResponse, error)
	GetBestProxy(context.Context, *GetBestProxyRequest) (*GetBestProxyResponse, error)
}

// UnimplementedProxyServer can be embedded to have forward compatible implementations.
type UnimplementedProxyServer struct {
}

func (*UnimplementedProxyServer) CreateProxy(ctx context.Context, req *CreateProxyRequest) (*CreateProxyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProxy not implemented")
}
func (*UnimplementedProxyServer) CreateProxyStat(ctx context.Context, req *CreateProxyStatRequest) (*CreateProxyStatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProxyStat not implemented")
}
func (*UnimplementedProxyServer) GetNextProxy(ctx context.Context, req *GetNextProxyRequest) (*GetNextProxyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNextProxy not implemented")
}
func (*UnimplementedProxyServer) GetBestProxy(ctx context.Context, req *GetBestProxyRequest) (*GetBestProxyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBestProxy not implemented")
}

func RegisterProxyServer(s *grpc.Server, srv ProxyServer) {
	s.RegisterService(&_Proxy_serviceDesc, srv)
}

func _Proxy_CreateProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).CreateProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gproxy.Proxy/CreateProxy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).CreateProxy(ctx, req.(*CreateProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_CreateProxyStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProxyStatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).CreateProxyStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gproxy.Proxy/CreateProxyStat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).CreateProxyStat(ctx, req.(*CreateProxyStatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_GetNextProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNextProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).GetNextProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gproxy.Proxy/GetNextProxy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).GetNextProxy(ctx, req.(*GetNextProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_GetBestProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBestProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).GetBestProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gproxy.Proxy/GetBestProxy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).GetBestProxy(ctx, req.(*GetBestProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Proxy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gproxy.Proxy",
	HandlerType: (*ProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProxy",
			Handler:    _Proxy_CreateProxy_Handler,
		},
		{
			MethodName: "CreateProxyStat",
			Handler:    _Proxy_CreateProxyStat_Handler,
		},
		{
			MethodName: "GetNextProxy",
			Handler:    _Proxy_GetNextProxy_Handler,
		},
		{
			MethodName: "GetBestProxy",
			Handler:    _Proxy_GetBestProxy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proxy.proto",
}

func (m *CreateProxyStatRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateProxyStatRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateProxyStatRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProxyStat != nil {
		{
			size, err := m.ProxyStat.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProxy(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CreateProxyStatResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateProxyStatResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateProxyStatResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProxyStat != nil {
		{
			size, err := m.ProxyStat.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProxy(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetNextProxyRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetNextProxyRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetNextProxyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetNextProxyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetNextProxyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetNextProxyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProxyItem != nil {
		{
			size, err := m.ProxyItem.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProxy(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetBestProxyRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetBestProxyRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetBestProxyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetBestProxyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetBestProxyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetBestProxyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProxyItem != nil {
		{
			size, err := m.ProxyItem.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProxy(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CreateProxyRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateProxyRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateProxyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProxyItem != nil {
		{
			size, err := m.ProxyItem.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProxy(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CreateProxyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateProxyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateProxyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProxyItem != nil {
		{
			size, err := m.ProxyItem.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProxy(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ProxyCountry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProxyCountry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProxyCountry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreatedAt != nil {
		n7, err7 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.CreatedAt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreatedAt):])
		if err7 != nil {
			return 0, err7
		}
		i -= n7
		i = encodeVarintProxy(dAtA, i, uint64(n7))
		i--
		dAtA[i] = 0x22
	}
	if len(m.CountryCode) > 0 {
		i -= len(m.CountryCode)
		copy(dAtA[i:], m.CountryCode)
		i = encodeVarintProxy(dAtA, i, uint64(len(m.CountryCode)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CountryName) > 0 {
		i -= len(m.CountryName)
		copy(dAtA[i:], m.CountryName)
		i = encodeVarintProxy(dAtA, i, uint64(len(m.CountryName)))
		i--
		dAtA[i] = 0x12
	}
	if m.CountryId != 0 {
		i = encodeVarintProxy(dAtA, i, uint64(m.CountryId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ProxyStat) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProxyStat) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProxyStat) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreatedAt != nil {
		n8, err8 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.CreatedAt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreatedAt):])
		if err8 != nil {
			return 0, err8
		}
		i -= n8
		i = encodeVarintProxy(dAtA, i, uint64(n8))
		i--
		dAtA[i] = 0x2a
	}
	if m.ConnStatus {
		i--
		if m.ConnStatus {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.ConnTime != 0 {
		i = encodeVarintProxy(dAtA, i, uint64(m.ConnTime))
		i--
		dAtA[i] = 0x18
	}
	if m.ProxyId != 0 {
		i = encodeVarintProxy(dAtA, i, uint64(m.ProxyId))
		i--
		dAtA[i] = 0x10
	}
	return len(dAtA) - i, nil
}

func (m *ProxyItem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProxyItem) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProxyItem) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DeletedAt != nil {
		n9, err9 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.DeletedAt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.DeletedAt):])
		if err9 != nil {
			return 0, err9
		}
		i -= n9
		i = encodeVarintProxy(dAtA, i, uint64(n9))
		i--
		dAtA[i] = 0x42
	}
	if m.UpdatedAt != nil {
		n10, err10 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.UpdatedAt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.UpdatedAt):])
		if err10 != nil {
			return 0, err10
		}
		i -= n10
		i = encodeVarintProxy(dAtA, i, uint64(n10))
		i--
		dAtA[i] = 0x3a
	}
	if m.CreatedAt != nil {
		n11, err11 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.CreatedAt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreatedAt):])
		if err11 != nil {
			return 0, err11
		}
		i -= n11
		i = encodeVarintProxy(dAtA, i, uint64(n11))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Anonymity) > 0 {
		i -= len(m.Anonymity)
		copy(dAtA[i:], m.Anonymity)
		i = encodeVarintProxy(dAtA, i, uint64(len(m.Anonymity)))
		i--
		dAtA[i] = 0x2a
	}
	if m.ProxyCountry != nil {
		{
			size, err := m.ProxyCountry.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProxy(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.ProxyPort != 0 {
		i = encodeVarintProxy(dAtA, i, uint64(m.ProxyPort))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ProxyIp) > 0 {
		i -= len(m.ProxyIp)
		copy(dAtA[i:], m.ProxyIp)
		i = encodeVarintProxy(dAtA, i, uint64(len(m.ProxyIp)))
		i--
		dAtA[i] = 0x12
	}
	if m.ProxyId != 0 {
		i = encodeVarintProxy(dAtA, i, uint64(m.ProxyId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintProxy(dAtA []byte, offset int, v uint64) int {
	offset -= sovProxy(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func NewPopulatedCreateProxyStatRequest(r randyProxy, easy bool) *CreateProxyStatRequest {
	this := &CreateProxyStatRequest{}
	if r.Intn(5) != 0 {
		this.ProxyStat = NewPopulatedProxyStat(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedCreateProxyStatResponse(r randyProxy, easy bool) *CreateProxyStatResponse {
	this := &CreateProxyStatResponse{}
	if r.Intn(5) != 0 {
		this.ProxyStat = NewPopulatedProxyStat(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedGetNextProxyRequest(r randyProxy, easy bool) *GetNextProxyRequest {
	this := &GetNextProxyRequest{}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedGetNextProxyResponse(r randyProxy, easy bool) *GetNextProxyResponse {
	this := &GetNextProxyResponse{}
	if r.Intn(5) != 0 {
		this.ProxyItem = NewPopulatedProxyItem(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedGetBestProxyRequest(r randyProxy, easy bool) *GetBestProxyRequest {
	this := &GetBestProxyRequest{}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedGetBestProxyResponse(r randyProxy, easy bool) *GetBestProxyResponse {
	this := &GetBestProxyResponse{}
	if r.Intn(5) != 0 {
		this.ProxyItem = NewPopulatedProxyItem(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedCreateProxyRequest(r randyProxy, easy bool) *CreateProxyRequest {
	this := &CreateProxyRequest{}
	if r.Intn(5) != 0 {
		this.ProxyItem = NewPopulatedProxyItem(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedCreateProxyResponse(r randyProxy, easy bool) *CreateProxyResponse {
	this := &CreateProxyResponse{}
	if r.Intn(5) != 0 {
		this.ProxyItem = NewPopulatedProxyItem(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedProxyCountry(r randyProxy, easy bool) *ProxyCountry {
	this := &ProxyCountry{}
	this.CountryId = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.CountryId *= -1
	}
	this.CountryName = string(randStringProxy(r))
	this.CountryCode = string(randStringProxy(r))
	if r.Intn(5) != 0 {
		this.CreatedAt = github_com_gogo_protobuf_types.NewPopulatedStdTime(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedProxyStat(r randyProxy, easy bool) *ProxyStat {
	this := &ProxyStat{}
	this.ProxyId = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.ProxyId *= -1
	}
	this.ConnTime = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.ConnTime *= -1
	}
	this.ConnStatus = bool(bool(r.Intn(2) == 0))
	if r.Intn(5) != 0 {
		this.CreatedAt = github_com_gogo_protobuf_types.NewPopulatedStdTime(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedProxyItem(r randyProxy, easy bool) *ProxyItem {
	this := &ProxyItem{}
	this.ProxyId = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.ProxyId *= -1
	}
	this.ProxyIp = string(randStringProxy(r))
	this.ProxyPort = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.ProxyPort *= -1
	}
	if r.Intn(5) != 0 {
		this.ProxyCountry = NewPopulatedProxyCountry(r, easy)
	}
	this.Anonymity = string(randStringProxy(r))
	if r.Intn(5) != 0 {
		this.CreatedAt = github_com_gogo_protobuf_types.NewPopulatedStdTime(r, easy)
	}
	if r.Intn(5) != 0 {
		this.UpdatedAt = github_com_gogo_protobuf_types.NewPopulatedStdTime(r, easy)
	}
	if r.Intn(5) != 0 {
		this.DeletedAt = github_com_gogo_protobuf_types.NewPopulatedStdTime(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyProxy interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneProxy(r randyProxy) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringProxy(r randyProxy) string {
	v1 := r.Intn(100)
	tmps := make([]rune, v1)
	for i := 0; i < v1; i++ {
		tmps[i] = randUTF8RuneProxy(r)
	}
	return string(tmps)
}
func randUnrecognizedProxy(r randyProxy, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldProxy(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldProxy(dAtA []byte, r randyProxy, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateProxy(dAtA, uint64(key))
		v2 := r.Int63()
		if r.Intn(2) == 0 {
			v2 *= -1
		}
		dAtA = encodeVarintPopulateProxy(dAtA, uint64(v2))
	case 1:
		dAtA = encodeVarintPopulateProxy(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateProxy(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateProxy(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateProxy(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateProxy(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *CreateProxyStatRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProxyStat != nil {
		l = m.ProxyStat.Size()
		n += 1 + l + sovProxy(uint64(l))
	}
	return n
}

func (m *CreateProxyStatResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProxyStat != nil {
		l = m.ProxyStat.Size()
		n += 1 + l + sovProxy(uint64(l))
	}
	return n
}

func (m *GetNextProxyRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetNextProxyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProxyItem != nil {
		l = m.ProxyItem.Size()
		n += 1 + l + sovProxy(uint64(l))
	}
	return n
}

func (m *GetBestProxyRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetBestProxyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProxyItem != nil {
		l = m.ProxyItem.Size()
		n += 1 + l + sovProxy(uint64(l))
	}
	return n
}

func (m *CreateProxyRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProxyItem != nil {
		l = m.ProxyItem.Size()
		n += 1 + l + sovProxy(uint64(l))
	}
	return n
}

func (m *CreateProxyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProxyItem != nil {
		l = m.ProxyItem.Size()
		n += 1 + l + sovProxy(uint64(l))
	}
	return n
}

func (m *ProxyCountry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CountryId != 0 {
		n += 1 + sovProxy(uint64(m.CountryId))
	}
	l = len(m.CountryName)
	if l > 0 {
		n += 1 + l + sovProxy(uint64(l))
	}
	l = len(m.CountryCode)
	if l > 0 {
		n += 1 + l + sovProxy(uint64(l))
	}
	if m.CreatedAt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreatedAt)
		n += 1 + l + sovProxy(uint64(l))
	}
	return n
}

func (m *ProxyStat) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProxyId != 0 {
		n += 1 + sovProxy(uint64(m.ProxyId))
	}
	if m.ConnTime != 0 {
		n += 1 + sovProxy(uint64(m.ConnTime))
	}
	if m.ConnStatus {
		n += 2
	}
	if m.CreatedAt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreatedAt)
		n += 1 + l + sovProxy(uint64(l))
	}
	return n
}

func (m *ProxyItem) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProxyId != 0 {
		n += 1 + sovProxy(uint64(m.ProxyId))
	}
	l = len(m.ProxyIp)
	if l > 0 {
		n += 1 + l + sovProxy(uint64(l))
	}
	if m.ProxyPort != 0 {
		n += 1 + sovProxy(uint64(m.ProxyPort))
	}
	if m.ProxyCountry != nil {
		l = m.ProxyCountry.Size()
		n += 1 + l + sovProxy(uint64(l))
	}
	l = len(m.Anonymity)
	if l > 0 {
		n += 1 + l + sovProxy(uint64(l))
	}
	if m.CreatedAt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreatedAt)
		n += 1 + l + sovProxy(uint64(l))
	}
	if m.UpdatedAt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.UpdatedAt)
		n += 1 + l + sovProxy(uint64(l))
	}
	if m.DeletedAt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.DeletedAt)
		n += 1 + l + sovProxy(uint64(l))
	}
	return n
}

func sovProxy(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozProxy(x uint64) (n int) {
	return sovProxy(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *CreateProxyStatRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CreateProxyStatRequest{`,
		`ProxyStat:` + strings.Replace(this.ProxyStat.String(), "ProxyStat", "ProxyStat", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CreateProxyStatResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CreateProxyStatResponse{`,
		`ProxyStat:` + strings.Replace(this.ProxyStat.String(), "ProxyStat", "ProxyStat", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetNextProxyRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetNextProxyRequest{`,
		`}`,
	}, "")
	return s
}
func (this *GetNextProxyResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetNextProxyResponse{`,
		`ProxyItem:` + strings.Replace(this.ProxyItem.String(), "ProxyItem", "ProxyItem", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetBestProxyRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetBestProxyRequest{`,
		`}`,
	}, "")
	return s
}
func (this *GetBestProxyResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetBestProxyResponse{`,
		`ProxyItem:` + strings.Replace(this.ProxyItem.String(), "ProxyItem", "ProxyItem", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CreateProxyRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CreateProxyRequest{`,
		`ProxyItem:` + strings.Replace(this.ProxyItem.String(), "ProxyItem", "ProxyItem", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CreateProxyResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CreateProxyResponse{`,
		`ProxyItem:` + strings.Replace(this.ProxyItem.String(), "ProxyItem", "ProxyItem", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ProxyCountry) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ProxyCountry{`,
		`CountryId:` + fmt.Sprintf("%v", this.CountryId) + `,`,
		`CountryName:` + fmt.Sprintf("%v", this.CountryName) + `,`,
		`CountryCode:` + fmt.Sprintf("%v", this.CountryCode) + `,`,
		`CreatedAt:` + strings.Replace(fmt.Sprintf("%v", this.CreatedAt), "Timestamp", "types.Timestamp", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ProxyStat) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ProxyStat{`,
		`ProxyId:` + fmt.Sprintf("%v", this.ProxyId) + `,`,
		`ConnTime:` + fmt.Sprintf("%v", this.ConnTime) + `,`,
		`ConnStatus:` + fmt.Sprintf("%v", this.ConnStatus) + `,`,
		`CreatedAt:` + strings.Replace(fmt.Sprintf("%v", this.CreatedAt), "Timestamp", "types.Timestamp", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ProxyItem) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ProxyItem{`,
		`ProxyId:` + fmt.Sprintf("%v", this.ProxyId) + `,`,
		`ProxyIp:` + fmt.Sprintf("%v", this.ProxyIp) + `,`,
		`ProxyPort:` + fmt.Sprintf("%v", this.ProxyPort) + `,`,
		`ProxyCountry:` + strings.Replace(this.ProxyCountry.String(), "ProxyCountry", "ProxyCountry", 1) + `,`,
		`Anonymity:` + fmt.Sprintf("%v", this.Anonymity) + `,`,
		`CreatedAt:` + strings.Replace(fmt.Sprintf("%v", this.CreatedAt), "Timestamp", "types.Timestamp", 1) + `,`,
		`UpdatedAt:` + strings.Replace(fmt.Sprintf("%v", this.UpdatedAt), "Timestamp", "types.Timestamp", 1) + `,`,
		`DeletedAt:` + strings.Replace(fmt.Sprintf("%v", this.DeletedAt), "Timestamp", "types.Timestamp", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringProxy(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *CreateProxyStatRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProxy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateProxyStatRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateProxyStatRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProxyStat", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProxy
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProxy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ProxyStat == nil {
				m.ProxyStat = &ProxyStat{}
			}
			if err := m.ProxyStat.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProxy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProxy
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthProxy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateProxyStatResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProxy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateProxyStatResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateProxyStatResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProxyStat", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProxy
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProxy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ProxyStat == nil {
				m.ProxyStat = &ProxyStat{}
			}
			if err := m.ProxyStat.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProxy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProxy
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthProxy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetNextProxyRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProxy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetNextProxyRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetNextProxyRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipProxy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProxy
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthProxy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetNextProxyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProxy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetNextProxyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetNextProxyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProxyItem", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProxy
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProxy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ProxyItem == nil {
				m.ProxyItem = &ProxyItem{}
			}
			if err := m.ProxyItem.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProxy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProxy
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthProxy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetBestProxyRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProxy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetBestProxyRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetBestProxyRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipProxy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProxy
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthProxy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetBestProxyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProxy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetBestProxyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetBestProxyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProxyItem", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProxy
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProxy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ProxyItem == nil {
				m.ProxyItem = &ProxyItem{}
			}
			if err := m.ProxyItem.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProxy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProxy
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthProxy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateProxyRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProxy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateProxyRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateProxyRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProxyItem", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProxy
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProxy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ProxyItem == nil {
				m.ProxyItem = &ProxyItem{}
			}
			if err := m.ProxyItem.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProxy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProxy
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthProxy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateProxyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProxy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateProxyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateProxyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProxyItem", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProxy
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProxy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ProxyItem == nil {
				m.ProxyItem = &ProxyItem{}
			}
			if err := m.ProxyItem.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProxy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProxy
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthProxy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProxyCountry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProxy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProxyCountry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProxyCountry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CountryId", wireType)
			}
			m.CountryId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CountryId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CountryName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProxy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProxy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CountryName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CountryCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProxy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProxy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CountryCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProxy
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProxy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreatedAt == nil {
				m.CreatedAt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProxy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProxy
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthProxy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProxyStat) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProxy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProxyStat: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProxyStat: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProxyId", wireType)
			}
			m.ProxyId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProxyId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnTime", wireType)
			}
			m.ConnTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConnTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnStatus", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ConnStatus = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProxy
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProxy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreatedAt == nil {
				m.CreatedAt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProxy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProxy
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthProxy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProxyItem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProxy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProxyItem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProxyItem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProxyId", wireType)
			}
			m.ProxyId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProxyId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProxyIp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProxy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProxy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProxyIp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProxyPort", wireType)
			}
			m.ProxyPort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProxyPort |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProxyCountry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProxy
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProxy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ProxyCountry == nil {
				m.ProxyCountry = &ProxyCountry{}
			}
			if err := m.ProxyCountry.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Anonymity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProxy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProxy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Anonymity = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProxy
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProxy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreatedAt == nil {
				m.CreatedAt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProxy
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProxy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UpdatedAt == nil {
				m.UpdatedAt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.UpdatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeletedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProxy
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProxy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeletedAt == nil {
				m.DeletedAt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.DeletedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProxy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProxy
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthProxy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProxy(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProxy
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProxy
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProxy
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthProxy
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupProxy
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthProxy
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthProxy        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProxy          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupProxy = fmt.Errorf("proto: unexpected end of group")
)
