// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxy.proto

package gproxy

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetNextProxyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNextProxyRequest) Reset()         { *m = GetNextProxyRequest{} }
func (m *GetNextProxyRequest) String() string { return proto.CompactTextString(m) }
func (*GetNextProxyRequest) ProtoMessage()    {}
func (*GetNextProxyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{0}
}

func (m *GetNextProxyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNextProxyRequest.Unmarshal(m, b)
}
func (m *GetNextProxyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNextProxyRequest.Marshal(b, m, deterministic)
}
func (m *GetNextProxyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNextProxyRequest.Merge(m, src)
}
func (m *GetNextProxyRequest) XXX_Size() int {
	return xxx_messageInfo_GetNextProxyRequest.Size(m)
}
func (m *GetNextProxyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNextProxyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNextProxyRequest proto.InternalMessageInfo

type GetNextProxyResponse struct {
	ProxyItem            *ProxyItem `protobuf:"bytes,1,opt,name=proxy_item,json=proxyItem,proto3" json:"proxy_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetNextProxyResponse) Reset()         { *m = GetNextProxyResponse{} }
func (m *GetNextProxyResponse) String() string { return proto.CompactTextString(m) }
func (*GetNextProxyResponse) ProtoMessage()    {}
func (*GetNextProxyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{1}
}

func (m *GetNextProxyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNextProxyResponse.Unmarshal(m, b)
}
func (m *GetNextProxyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNextProxyResponse.Marshal(b, m, deterministic)
}
func (m *GetNextProxyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNextProxyResponse.Merge(m, src)
}
func (m *GetNextProxyResponse) XXX_Size() int {
	return xxx_messageInfo_GetNextProxyResponse.Size(m)
}
func (m *GetNextProxyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNextProxyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNextProxyResponse proto.InternalMessageInfo

func (m *GetNextProxyResponse) GetProxyItem() *ProxyItem {
	if m != nil {
		return m.ProxyItem
	}
	return nil
}

type GetBestProxyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBestProxyRequest) Reset()         { *m = GetBestProxyRequest{} }
func (m *GetBestProxyRequest) String() string { return proto.CompactTextString(m) }
func (*GetBestProxyRequest) ProtoMessage()    {}
func (*GetBestProxyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{2}
}

func (m *GetBestProxyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBestProxyRequest.Unmarshal(m, b)
}
func (m *GetBestProxyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBestProxyRequest.Marshal(b, m, deterministic)
}
func (m *GetBestProxyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBestProxyRequest.Merge(m, src)
}
func (m *GetBestProxyRequest) XXX_Size() int {
	return xxx_messageInfo_GetBestProxyRequest.Size(m)
}
func (m *GetBestProxyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBestProxyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBestProxyRequest proto.InternalMessageInfo

type GetBestProxyResponse struct {
	ProxyItem            *ProxyItem `protobuf:"bytes,1,opt,name=proxy_item,json=proxyItem,proto3" json:"proxy_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetBestProxyResponse) Reset()         { *m = GetBestProxyResponse{} }
func (m *GetBestProxyResponse) String() string { return proto.CompactTextString(m) }
func (*GetBestProxyResponse) ProtoMessage()    {}
func (*GetBestProxyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{3}
}

func (m *GetBestProxyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBestProxyResponse.Unmarshal(m, b)
}
func (m *GetBestProxyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBestProxyResponse.Marshal(b, m, deterministic)
}
func (m *GetBestProxyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBestProxyResponse.Merge(m, src)
}
func (m *GetBestProxyResponse) XXX_Size() int {
	return xxx_messageInfo_GetBestProxyResponse.Size(m)
}
func (m *GetBestProxyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBestProxyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBestProxyResponse proto.InternalMessageInfo

func (m *GetBestProxyResponse) GetProxyItem() *ProxyItem {
	if m != nil {
		return m.ProxyItem
	}
	return nil
}

type CreateProxyRequest struct {
	ProxyItem            *ProxyItem `protobuf:"bytes,1,opt,name=proxy_item,json=proxyItem,proto3" json:"proxy_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateProxyRequest) Reset()         { *m = CreateProxyRequest{} }
func (m *CreateProxyRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProxyRequest) ProtoMessage()    {}
func (*CreateProxyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{4}
}

func (m *CreateProxyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProxyRequest.Unmarshal(m, b)
}
func (m *CreateProxyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProxyRequest.Marshal(b, m, deterministic)
}
func (m *CreateProxyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProxyRequest.Merge(m, src)
}
func (m *CreateProxyRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProxyRequest.Size(m)
}
func (m *CreateProxyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProxyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProxyRequest proto.InternalMessageInfo

func (m *CreateProxyRequest) GetProxyItem() *ProxyItem {
	if m != nil {
		return m.ProxyItem
	}
	return nil
}

type CreateProxyResponse struct {
	ProxyItem            *ProxyItem `protobuf:"bytes,1,opt,name=proxy_item,json=proxyItem,proto3" json:"proxy_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateProxyResponse) Reset()         { *m = CreateProxyResponse{} }
func (m *CreateProxyResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProxyResponse) ProtoMessage()    {}
func (*CreateProxyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{5}
}

func (m *CreateProxyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProxyResponse.Unmarshal(m, b)
}
func (m *CreateProxyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProxyResponse.Marshal(b, m, deterministic)
}
func (m *CreateProxyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProxyResponse.Merge(m, src)
}
func (m *CreateProxyResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProxyResponse.Size(m)
}
func (m *CreateProxyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProxyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProxyResponse proto.InternalMessageInfo

func (m *CreateProxyResponse) GetProxyItem() *ProxyItem {
	if m != nil {
		return m.ProxyItem
	}
	return nil
}

type ProxyCountry struct {
	CountryId            int64                `protobuf:"varint,1,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	CountryName          string               `protobuf:"bytes,2,opt,name=country_name,json=countryName,proto3" json:"country_name,omitempty"`
	CountryCode          string               `protobuf:"bytes,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProxyCountry) Reset()         { *m = ProxyCountry{} }
func (m *ProxyCountry) String() string { return proto.CompactTextString(m) }
func (*ProxyCountry) ProtoMessage()    {}
func (*ProxyCountry) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{6}
}

func (m *ProxyCountry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyCountry.Unmarshal(m, b)
}
func (m *ProxyCountry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyCountry.Marshal(b, m, deterministic)
}
func (m *ProxyCountry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyCountry.Merge(m, src)
}
func (m *ProxyCountry) XXX_Size() int {
	return xxx_messageInfo_ProxyCountry.Size(m)
}
func (m *ProxyCountry) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyCountry.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyCountry proto.InternalMessageInfo

func (m *ProxyCountry) GetCountryId() int64 {
	if m != nil {
		return m.CountryId
	}
	return 0
}

func (m *ProxyCountry) GetCountryName() string {
	if m != nil {
		return m.CountryName
	}
	return ""
}

func (m *ProxyCountry) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *ProxyCountry) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type ProxyStat struct {
	StatId               int64                `protobuf:"varint,1,opt,name=stat_id,json=statId,proto3" json:"stat_id,omitempty"`
	ProxyId              int64                `protobuf:"varint,2,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	ConnTime             int64                `protobuf:"varint,3,opt,name=conn_time,json=connTime,proto3" json:"conn_time,omitempty"`
	ConnStatus           bool                 `protobuf:"varint,4,opt,name=conn_status,json=connStatus,proto3" json:"conn_status,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProxyStat) Reset()         { *m = ProxyStat{} }
func (m *ProxyStat) String() string { return proto.CompactTextString(m) }
func (*ProxyStat) ProtoMessage()    {}
func (*ProxyStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{7}
}

func (m *ProxyStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyStat.Unmarshal(m, b)
}
func (m *ProxyStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyStat.Marshal(b, m, deterministic)
}
func (m *ProxyStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyStat.Merge(m, src)
}
func (m *ProxyStat) XXX_Size() int {
	return xxx_messageInfo_ProxyStat.Size(m)
}
func (m *ProxyStat) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyStat.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyStat proto.InternalMessageInfo

func (m *ProxyStat) GetStatId() int64 {
	if m != nil {
		return m.StatId
	}
	return 0
}

func (m *ProxyStat) GetProxyId() int64 {
	if m != nil {
		return m.ProxyId
	}
	return 0
}

func (m *ProxyStat) GetConnTime() int64 {
	if m != nil {
		return m.ConnTime
	}
	return 0
}

func (m *ProxyStat) GetConnStatus() bool {
	if m != nil {
		return m.ConnStatus
	}
	return false
}

func (m *ProxyStat) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type ProxyItem struct {
	ProxyId              int64                `protobuf:"varint,1,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	ProxyIp              string               `protobuf:"bytes,2,opt,name=proxy_ip,json=proxyIp,proto3" json:"proxy_ip,omitempty"`
	ProxyPort            int64                `protobuf:"varint,3,opt,name=proxy_port,json=proxyPort,proto3" json:"proxy_port,omitempty"`
	Anonymity            string               `protobuf:"bytes,5,opt,name=anonymity,proto3" json:"anonymity,omitempty"`
	ProxyCountry         *ProxyCountry        `protobuf:"bytes,4,opt,name=proxy_country,json=proxyCountry,proto3" json:"proxy_country,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProxyItem) Reset()         { *m = ProxyItem{} }
func (m *ProxyItem) String() string { return proto.CompactTextString(m) }
func (*ProxyItem) ProtoMessage()    {}
func (*ProxyItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{8}
}

func (m *ProxyItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyItem.Unmarshal(m, b)
}
func (m *ProxyItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyItem.Marshal(b, m, deterministic)
}
func (m *ProxyItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyItem.Merge(m, src)
}
func (m *ProxyItem) XXX_Size() int {
	return xxx_messageInfo_ProxyItem.Size(m)
}
func (m *ProxyItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyItem.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyItem proto.InternalMessageInfo

func (m *ProxyItem) GetProxyId() int64 {
	if m != nil {
		return m.ProxyId
	}
	return 0
}

func (m *ProxyItem) GetProxyIp() string {
	if m != nil {
		return m.ProxyIp
	}
	return ""
}

func (m *ProxyItem) GetProxyPort() int64 {
	if m != nil {
		return m.ProxyPort
	}
	return 0
}

func (m *ProxyItem) GetAnonymity() string {
	if m != nil {
		return m.Anonymity
	}
	return ""
}

func (m *ProxyItem) GetProxyCountry() *ProxyCountry {
	if m != nil {
		return m.ProxyCountry
	}
	return nil
}

func (m *ProxyItem) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ProxyItem) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *ProxyItem) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*GetNextProxyRequest)(nil), "gproxy.GetNextProxyRequest")
	proto.RegisterType((*GetNextProxyResponse)(nil), "gproxy.GetNextProxyResponse")
	proto.RegisterType((*GetBestProxyRequest)(nil), "gproxy.GetBestProxyRequest")
	proto.RegisterType((*GetBestProxyResponse)(nil), "gproxy.GetBestProxyResponse")
	proto.RegisterType((*CreateProxyRequest)(nil), "gproxy.CreateProxyRequest")
	proto.RegisterType((*CreateProxyResponse)(nil), "gproxy.CreateProxyResponse")
	proto.RegisterType((*ProxyCountry)(nil), "gproxy.ProxyCountry")
	proto.RegisterType((*ProxyStat)(nil), "gproxy.ProxyStat")
	proto.RegisterType((*ProxyItem)(nil), "gproxy.ProxyItem")
}

func init() {
	proto.RegisterFile("proxy.proto", fileDescriptor_700b50b08ed8dbaf)
}

var fileDescriptor_700b50b08ed8dbaf = []byte{
	// 501 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x4e, 0xdb, 0x40,
	0x10, 0xc6, 0xa4, 0x24, 0xf1, 0x38, 0x3d, 0x74, 0xa1, 0x6a, 0x6a, 0xa8, 0xa0, 0x3e, 0x71, 0x32,
	0x15, 0x3d, 0x71, 0xa4, 0x91, 0x0a, 0x51, 0x25, 0x84, 0x96, 0xde, 0x23, 0x93, 0x9d, 0x46, 0x91,
	0xb0, 0x77, 0x6b, 0x8f, 0x25, 0xf2, 0x52, 0x3d, 0xf7, 0x99, 0xda, 0x97, 0x40, 0xfb, 0x63, 0xe2,
	0x0d, 0x91, 0x50, 0x72, 0xb3, 0xbf, 0x99, 0xf9, 0xe6, 0x9b, 0x9f, 0x1d, 0x88, 0x54, 0x29, 0x1f,
	0x17, 0xa9, 0x2a, 0x25, 0x49, 0xd6, 0x9d, 0x99, 0xbf, 0xf8, 0x78, 0x26, 0xe5, 0xec, 0x01, 0xcf,
	0x0c, 0x7a, 0x5f, 0xff, 0x3a, 0xa3, 0x79, 0x8e, 0x15, 0x65, 0xb9, 0xb2, 0x8e, 0xc9, 0x7b, 0xd8,
	0xbf, 0x42, 0xba, 0xc1, 0x47, 0xba, 0xd5, 0x01, 0x1c, 0x7f, 0xd7, 0x58, 0x51, 0x72, 0x0d, 0x07,
	0x3e, 0x5c, 0x29, 0x59, 0x54, 0xc8, 0xbe, 0x00, 0x18, 0xe2, 0xc9, 0x9c, 0x30, 0x1f, 0x06, 0x27,
	0xc1, 0x69, 0x74, 0xfe, 0x2e, 0xb5, 0xc9, 0x52, 0xe3, 0x3a, 0x26, 0xcc, 0x79, 0xa8, 0x9a, 0x4f,
	0x97, 0xe0, 0x1b, 0x56, 0xeb, 0x12, 0xb4, 0xe0, 0xad, 0x13, 0x7c, 0x07, 0x36, 0x2a, 0x31, 0x23,
	0x6c, 0xf3, 0x6f, 0xc1, 0x73, 0x05, 0xfb, 0x1e, 0xcf, 0xd6, 0x82, 0xfe, 0x04, 0x30, 0x30, 0x86,
	0x91, 0xac, 0x0b, 0x2a, 0x17, 0xec, 0x13, 0xc0, 0xd4, 0x7e, 0x4e, 0xe6, 0xc2, 0x50, 0x74, 0x78,
	0xe8, 0x90, 0xb1, 0x60, 0x9f, 0x61, 0xd0, 0x98, 0x8b, 0x2c, 0xc7, 0xe1, 0xee, 0x49, 0x70, 0x1a,
	0xf2, 0xc8, 0x61, 0x37, 0x59, 0x8e, 0x6d, 0x97, 0xa9, 0x14, 0x38, 0xec, 0x78, 0x2e, 0x23, 0x29,
	0x90, 0x5d, 0x00, 0x4c, 0x8d, 0x7c, 0x31, 0xc9, 0x68, 0xf8, 0xc6, 0xe8, 0x8c, 0x53, 0x3b, 0xfe,
	0xb4, 0x19, 0x7f, 0xfa, 0xb3, 0x19, 0x3f, 0x0f, 0x9d, 0xf7, 0x25, 0x25, 0x7f, 0x03, 0x08, 0x8d,
	0xe0, 0x3b, 0xca, 0x88, 0x7d, 0x80, 0x5e, 0x45, 0x19, 0x2d, 0xa5, 0x76, 0xf5, 0xef, 0x58, 0xb0,
	0x8f, 0xd0, 0x77, 0x9d, 0x10, 0x46, 0x63, 0x87, 0xf7, 0x6c, 0xd1, 0x82, 0x1d, 0x42, 0x38, 0x95,
	0x45, 0x31, 0xd1, 0xdb, 0x65, 0xc4, 0x75, 0x78, 0x5f, 0x03, 0x3a, 0x1d, 0x3b, 0x86, 0xc8, 0x18,
	0x35, 0x4d, 0x5d, 0x19, 0x69, 0x7d, 0x0e, 0x1a, 0xba, 0x33, 0xc8, 0x8a, 0xf4, 0xbd, 0x4d, 0xa4,
	0xff, 0xdb, 0x75, 0xd2, 0x75, 0xe7, 0x3d, 0x85, 0x81, 0xaf, 0x70, 0x69, 0x52, 0xae, 0xc1, 0xce,
	0xa4, 0xf4, 0x78, 0xac, 0x49, 0xc9, 0x92, 0x9c, 0x7a, 0x3b, 0xce, 0x5b, 0x59, 0x12, 0x3b, 0x82,
	0x30, 0x2b, 0x64, 0xb1, 0xc8, 0xe7, 0xb4, 0x30, 0xe2, 0x42, 0xbe, 0x04, 0xd8, 0x05, 0xbc, 0xb5,
	0xc1, 0x6e, 0x16, 0xae, 0xf3, 0x07, 0xde, 0x86, 0xb8, 0x45, 0xe0, 0x03, 0xd5, 0x5e, 0x0b, 0xbf,
	0xec, 0xee, 0x06, 0x65, 0xeb, 0xd0, 0x5a, 0x89, 0x26, 0xb4, 0xf7, 0x7a, 0xa8, 0xf3, 0xb6, 0xa1,
	0x02, 0x1f, 0xd0, 0x85, 0xf6, 0x5f, 0x0f, 0x75, 0xde, 0x97, 0x74, 0xfe, 0x3f, 0x80, 0x3d, 0x53,
	0x0f, 0xbb, 0x86, 0xa8, 0xf5, 0x56, 0x58, 0xdc, 0x54, 0xfb, 0xf2, 0x21, 0xc6, 0x87, 0x6b, 0x6d,
	0xf6, 0x71, 0x25, 0x3b, 0xec, 0x07, 0x0c, 0xda, 0x77, 0x80, 0x3d, 0xbb, 0xaf, 0x39, 0x1a, 0xf1,
	0xd1, 0x7a, 0xe3, 0x0a, 0xd9, 0xf3, 0xd5, 0xf2, 0xc8, 0x56, 0x4f, 0x9c, 0x47, 0xf6, 0xe2, 0xd0,
	0x25, 0x3b, 0xf7, 0x5d, 0xd3, 0x8c, 0xaf, 0x4f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4e, 0xb7, 0xad,
	0xc8, 0x58, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProxyClient is the client API for Proxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProxyClient interface {
	CreateProxy(ctx context.Context, in *CreateProxyRequest, opts ...grpc.CallOption) (*CreateProxyResponse, error)
	GetBestProxy(ctx context.Context, in *GetBestProxyRequest, opts ...grpc.CallOption) (*GetBestProxyResponse, error)
	GetNextProxy(ctx context.Context, in *GetNextProxyRequest, opts ...grpc.CallOption) (*GetNextProxyResponse, error)
}

type proxyClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyClient(cc grpc.ClientConnInterface) ProxyClient {
	return &proxyClient{cc}
}

func (c *proxyClient) CreateProxy(ctx context.Context, in *CreateProxyRequest, opts ...grpc.CallOption) (*CreateProxyResponse, error) {
	out := new(CreateProxyResponse)
	err := c.cc.Invoke(ctx, "/gproxy.Proxy/CreateProxy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) GetBestProxy(ctx context.Context, in *GetBestProxyRequest, opts ...grpc.CallOption) (*GetBestProxyResponse, error) {
	out := new(GetBestProxyResponse)
	err := c.cc.Invoke(ctx, "/gproxy.Proxy/GetBestProxy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) GetNextProxy(ctx context.Context, in *GetNextProxyRequest, opts ...grpc.CallOption) (*GetNextProxyResponse, error) {
	out := new(GetNextProxyResponse)
	err := c.cc.Invoke(ctx, "/gproxy.Proxy/GetNextProxy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyServer is the Server API for Proxy service.
type ProxyServer interface {
	CreateProxy(context.Context, *CreateProxyRequest) (*CreateProxyResponse, error)
	GetBestProxy(context.Context, *GetBestProxyRequest) (*GetBestProxyResponse, error)
	GetNextProxy(context.Context, *GetNextProxyRequest) (*GetNextProxyResponse, error)
}

// UnimplementedProxyServer can be embedded to have forward compatible implementations.
type UnimplementedProxyServer struct {
}

func (*UnimplementedProxyServer) CreateProxy(ctx context.Context, req *CreateProxyRequest) (*CreateProxyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProxy not implemented")
}
func (*UnimplementedProxyServer) GetBestProxy(ctx context.Context, req *GetBestProxyRequest) (*GetBestProxyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBestProxy not implemented")
}
func (*UnimplementedProxyServer) GetNextProxy(ctx context.Context, req *GetNextProxyRequest) (*GetNextProxyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNextProxy not implemented")
}

func RegisterProxyServer(s *grpc.Server, srv ProxyServer) {
	s.RegisterService(&_Proxy_serviceDesc, srv)
}

func _Proxy_CreateProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).CreateProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gproxy.Proxy/CreateProxy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).CreateProxy(ctx, req.(*CreateProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_GetBestProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBestProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).GetBestProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gproxy.Proxy/GetBestProxy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).GetBestProxy(ctx, req.(*GetBestProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_GetNextProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNextProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).GetNextProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gproxy.Proxy/GetNextProxy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).GetNextProxy(ctx, req.(*GetNextProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Proxy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gproxy.Proxy",
	HandlerType: (*ProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProxy",
			Handler:    _Proxy_CreateProxy_Handler,
		},
		{
			MethodName: "GetBestProxy",
			Handler:    _Proxy_GetBestProxy_Handler,
		},
		{
			MethodName: "GetNextProxy",
			Handler:    _Proxy_GetNextProxy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proxy.proto",
}
